/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    berita: Berita;
    programs: Program;
    publikasi: Publikasi;
    situs: Situs;
    artefak: Artefak;
    'karya-museum': KaryaMuseum;
    'karya-publik': KaryaPublik;
    pages: Page;
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    berita: BeritaSelect<false> | BeritaSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    publikasi: PublikasiSelect<false> | PublikasiSelect<true>;
    situs: SitusSelect<false> | SitusSelect<true>;
    artefak: ArtefakSelect<false> | ArtefakSelect<true>;
    'karya-museum': KaryaMuseumSelect<false> | KaryaMuseumSelect<true>;
    'karya-publik': KaryaPublikSelect<false> | KaryaPublikSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('id' | 'en') | ('id' | 'en')[];
  globals: {
    navigation: Navigation;
    'site-settings': SiteSetting;
    'page-beranda': PageBeranda;
    'page-tentang': PageTentang;
    'page-konservasi': PageKonservasi;
  };
  globalsSelect: {
    navigation: NavigationSelect<false> | NavigationSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'page-beranda': PageBerandaSelect<false> | PageBerandaSelect<true>;
    'page-tentang': PageTentangSelect<false> | PageTentangSelect<true>;
    'page-konservasi': PageKonservasiSelect<false> | PageKonservasiSelect<true>;
  };
  locale: 'id' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Kelola warta berita, liputan lapangan, dan kabar kebudayaan Majapahit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "berita".
 */
export interface Berita {
  id: number;
  title: string;
  /**
   * Disarankan foto landscape beresolusi baik dengan rasio 16:9.
   */
  coverImage?: (number | null) | Media;
  /**
   * Ringkasan singkat (2–3 kalimat) yang muncul pada kartu pratinjau halaman beranda.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status?: ('draft' | 'published') | null;
  publishedAt?: string | null;
  /**
   * Otomatis terisi akun kurator saat diterbitkan.
   */
  author?: string | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pusat penyimpanan foto, gambar koleksi, dan aset visual situs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Deskripsi gambar untuk aksesibilitas pembaca layar dan optimasi SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Kelola pameran virtual 3D, workshop, webinar, pertunjukan, dan simposium kebudayaan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  title: string;
  /**
   * Poster atau foto representasi kegiatan beresolusi baik.
   */
  coverImage?: (number | null) | Media;
  /**
   * Ringkasan singkat acara yang tampil pada kartu pratinjau dan beranda.
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  status?: ('draft' | 'published') | null;
  /**
   * Menentukan jenis dan klasifikasi agenda museum.
   */
  programType:
    | 'Pameran Virtual'
    | 'Pameran Karya'
    | 'Program Edukasi'
    | 'Pertunjukan Budaya'
    | 'Workshop & Pelatihan'
    | 'Seminar & Simposium';
  /**
   * Kosongkan jika jadwal belum ditentukan (Segera Hadir).
   */
  eventDate?: string | null;
  /**
   * Diisi jika acara berlangsung beberapa hari/bulan (periode pameran).
   */
  eventEndDate?: string | null;
  location?: string | null;
  ctaLabel?: string | null;
  /**
   * Jika diisi (misal: link Zoom/Google Form), tombol akan membuka tautan ini.
   */
  ctaUrl?: string | null;
  publishedAt?: string | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelola repositori jurnal penelitian, buku monograf, dan prosiding ilmiah Majapahit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publikasi".
 */
export interface Publikasi {
  id: number;
  title: string;
  abstract: string;
  status?: ('draft' | 'published') | null;
  year: string;
  publicationName: string;
  volume?: string | null;
  issue?: string | null;
  pages?: string | null;
  typeBadge:
    | 'Jurnal Ilmiah Nasional'
    | 'Jurnal Terakreditasi'
    | 'Jurnal Internasional'
    | 'Prosiding Simposium'
    | 'Buku & Monograf'
    | 'Laporan Arkeologis';
  sintaBadge?: ('SINTA 1' | 'SINTA 2' | 'SINTA 3' | 'SINTA 4' | 'Scopus' | 'Non-SINTA') | null;
  doi?: string | null;
  externalUrl: string;
  pdfUrl?: string | null;
  authors?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  keywords?:
    | {
        keyword: string;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Pusat data dokumentasi situs dan arsitektur peninggalan era Majapahit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "situs".
 */
export interface Situs {
  id: number;
  name: string;
  slug: string;
  location: string;
  era: string;
  status?: ('Terdokumentasi' | 'Pemindaian 3D' | 'Dalam Proses') | null;
  image?: (number | null) | Media;
  description: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Inventarisasi artefak, arca, tosan aji, dan benda cagar budaya.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artefak".
 */
export interface Artefak {
  id: number;
  name: string;
  slug: string;
  category: 'Prasasti & Inskripsi' | 'Arca & Patung' | 'Keramik & Gerabah' | 'Perhiasan & Logam' | 'Naskah & Sastra';
  era: string;
  material: string;
  image?: (number | null) | Media;
  description: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Katalog pameran karya museum: koleksi otentik dan karya kontemporer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "karya-museum".
 */
export interface KaryaMuseum {
  id: number;
  title: string;
  slug: string;
  type: 'otentik' | 'kontemporer';
  image: number | Media;
  creator?: string | null;
  era?: string | null;
  material?: string | null;
  description?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tinjau dan kurasi kiriman karya seni dari masyarakat dan sivitas akademika.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "karya-publik".
 */
export interface KaryaPublik {
  id: number;
  title: string;
  contributorName: string;
  contributorEmail: string;
  contributorAffiliation?: string | null;
  category: 'seni-rupa' | 'desain-ilustrasi' | 'fotografi' | 'model-3d' | 'riset-visual' | 'lainnya';
  description: string;
  image: number | Media;
  status?: ('pending' | 'published' | 'rejected') | null;
  /**
   * Hanya dapat dilihat oleh pengelola / tim kurator PUI
   */
  moderationNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelola konten halaman khusus dan laman statis tambahan.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL slug untuk halaman ini (misal: faq, kemitraan, panduan)
   */
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kelola akun pengguna dan hak akses sistem.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Nama yang dicantumkan sebagai identitas dan atribusi penulis.
   */
  name: string;
  role: 'admin' | 'staff';
  /**
   * Jabatan resmi atau spesialisasi di lingkungan PUI Seni Budaya Majapahitan.
   */
  title?: string | null;
  /**
   * Foto identitas profil pengguna (disarankan foto portrait rasio 1:1).
   */
  avatar?: (number | null) | Media;
  /**
   * Biografi atau profil singkat pengelola untuk kebutuhan pengenalan penulis.
   */
  bio?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'berita';
        value: number | Berita;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'publikasi';
        value: number | Publikasi;
      } | null)
    | ({
        relationTo: 'situs';
        value: number | Situs;
      } | null)
    | ({
        relationTo: 'artefak';
        value: number | Artefak;
      } | null)
    | ({
        relationTo: 'karya-museum';
        value: number | KaryaMuseum;
      } | null)
    | ({
        relationTo: 'karya-publik';
        value: number | KaryaPublik;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "berita_select".
 */
export interface BeritaSelect<T extends boolean = true> {
  title?: T;
  coverImage?: T;
  excerpt?: T;
  content?: T;
  status?: T;
  publishedAt?: T;
  author?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  title?: T;
  coverImage?: T;
  excerpt?: T;
  content?: T;
  status?: T;
  programType?: T;
  eventDate?: T;
  eventEndDate?: T;
  location?: T;
  ctaLabel?: T;
  ctaUrl?: T;
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publikasi_select".
 */
export interface PublikasiSelect<T extends boolean = true> {
  title?: T;
  abstract?: T;
  status?: T;
  year?: T;
  publicationName?: T;
  volume?: T;
  issue?: T;
  pages?: T;
  typeBadge?: T;
  sintaBadge?: T;
  doi?: T;
  externalUrl?: T;
  pdfUrl?: T;
  authors?:
    | T
    | {
        name?: T;
        id?: T;
      };
  keywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  publishedAt?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "situs_select".
 */
export interface SitusSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  location?: T;
  era?: T;
  status?: T;
  image?: T;
  description?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "artefak_select".
 */
export interface ArtefakSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  era?: T;
  material?: T;
  image?: T;
  description?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "karya-museum_select".
 */
export interface KaryaMuseumSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  type?: T;
  image?: T;
  creator?: T;
  era?: T;
  material?: T;
  description?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "karya-publik_select".
 */
export interface KaryaPublikSelect<T extends boolean = true> {
  title?: T;
  contributorName?: T;
  contributorEmail?: T;
  contributorAffiliation?: T;
  category?: T;
  description?: T;
  image?: T;
  status?: T;
  moderationNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  title?: T;
  avatar?: T;
  bio?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Kelola hierarki dan tautan menu navigasi utama website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Identitas institusi, kontak resmi, alamat, jam operasional, dan akun media sosial.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  org: string;
  university: string;
  operatingHours?: string | null;
  office?: string | null;
  email?: string | null;
  googleMapsUrl?: string | null;
  socials?:
    | {
        label: string;
        href: string;
        handle: string;
        icon: 'instagram' | 'youtube' | 'twitter' | 'facebook';
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Pengaturan konten dinamis untuk Landing Page Beranda (/)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-beranda".
 */
export interface PageBeranda {
  id: number;
  heroSlides?:
    | {
        title: string;
        subtitle: string;
        image?: (number | null) | Media;
        primaryLabel?: string | null;
        primaryHref?: string | null;
        secondaryLabel?: string | null;
        secondaryHref?: string | null;
        id?: string | null;
      }[]
    | null;
  tentangEyebrow?: string | null;
  tentangTitle?: string | null;
  tentangBody?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Pengaturan konten untuk Halaman Tentang Museum (/tentang)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-tentang".
 */
export interface PageTentang {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  visi?: string | null;
  misi?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  sejarahParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Pengaturan konten untuk Halaman Indeks Museum Konservasi (/konservasi)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-konservasi".
 */
export interface PageKonservasi {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  pengantarParagraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  org?: T;
  university?: T;
  operatingHours?: T;
  office?: T;
  email?: T;
  googleMapsUrl?: T;
  socials?:
    | T
    | {
        label?: T;
        href?: T;
        handle?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-beranda_select".
 */
export interface PageBerandaSelect<T extends boolean = true> {
  heroSlides?:
    | T
    | {
        title?: T;
        subtitle?: T;
        image?: T;
        primaryLabel?: T;
        primaryHref?: T;
        secondaryLabel?: T;
        secondaryHref?: T;
        id?: T;
      };
  tentangEyebrow?: T;
  tentangTitle?: T;
  tentangBody?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-tentang_select".
 */
export interface PageTentangSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  visi?: T;
  misi?:
    | T
    | {
        point?: T;
        id?: T;
      };
  sejarahParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-konservasi_select".
 */
export interface PageKonservasiSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  pengantarParagraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}